type: spot_grid
symbol: LIT/USDC
upper_price: 2.9
lower_price:  2.6
grid_type: Geometric # Arithmetic or Geometric
grid_count: 55
total_investment: 40000
trigger_price: 2.7 # Optional: Wait for price to hit this before starting
