type: spot_grid
symbol: LIT/USDC
grid_range_high: 2.9
grid_range_low:  2.6
grid_type: Geometric # Arithmetic or Geometric
grid_count: 55
total_investment: 40000
trigger_price: 2.7 # Optional: Wait for price to hit this before starting
